### ISSUE TITLE
Letters on button not displayed in Evolution email client

### ISSUE THREAD

**Issue by danijo01** [EliverLara/Ant-Nebula#1]
I'm using Ubuntu Gnome 16.04 (GNOME Shell 3.20.4).
In Evolution email client, when I receive emails that contain the buttons to "open calendar", "accept", etc, the button letters are not well displayed.

![selection_022](https://user-images.githubusercontent.com/7268314/35911859-4daa9734-0bfb-11e8-9b02-bbe8d0312aae.png)

![selection_025](https://user-images.githubusercontent.com/7268314/35912097-e4da1738-0bfb-11e8-97db-18f4d8315fc1.png)

When you put the mouse over the button, the letters appear
![selection_024](https://user-images.githubusercontent.com/7268314/35911950-8974b182-0bfb-11e8-8817-ce8395e555d4.png)

Thanks

**Comment by EliverLara** [comment]
Hi, thanks for reporting, could you tell me how to get those buttons please?

**Comment by danijo01** [comment]
Sending a new meeting invitation for example.
_https://help.gnome.org/users/evolution/stable/calendar-meetings-sending-invitation.html.en_

Thanks

**Comment by EliverLara** [comment]
Seems to be a bug in evolution itself.
Uses the .button:active color setting in all states while background-color does change.
Checked on multiple themes.

This is fixed by changing the  .button:active color for a dark one, but it doesn't look good on the rest of the buttons, if you wanna do the trick by yourself just run the following in your terminal:
 ` echo -e "\n\nbutton:active{ color: #31363D; }" >> path-to-Ant-Nebula/gtk-3.20/gtk.css`

**Comment by danijo01** [comment]
For me, it's ok. Thank you.
